version: "3.1"
services:
  clarisa_wos_mysql:
    container_name: clarisa_wos_mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mqap
      MYSQL_PASSWORD: root
    volumes:
      - ./mysqlData:/var/lib/mysql
  clarisa_wos_api:
    container_name: clarisa_wos_api
    depends_on:
      - clarisa_wos_mysql
    build:
      context: ./back-end
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./back-end/media:/back-end/media
      - ./back-end/uploads:/back-end/uploads
  clarisa_wos_front_end:
    container_name: clarisa_wos_front_end
    build: front-end
    restart: always
    links:
      - clarisa_wos_api
    depends_on:
      - clarisa_wos_mysql
      - clarisa_wos_api
    ports:
      - 9981:80